sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t test-docker-react . 

script:
  - docker run -e CI=true test-docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "test-docker-react-2" 
  env: "TestDockerReact2-env"
  bucket_name: "elasticbeanstalk-eu-west-1-686188186368"
  bucket_path: "test-docker-react-2" 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET

