sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t test-docker-react . 

script:
  - docker run -e CI=true test-docker-react yarn test -- --coverage
